version: '3.9'

services:
  revel-pg-testtask:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - .:/app
    environment:
      - ENV=dev
      - PORT=8090
      - DB_URL=postgres://postgres:root@db/book_store?sslmode=disable
    depends_on:
      - db
    restart: always

  db:
    container_name: database
    image: postgres:12
    environment:
      POSTGRES_HOST: postgres # имя хоста/адрес (для локального подключения - "localhost", для докера - "postgres")
      POSTGRES_DB: book_store # название самой базы (нужно предварительно создать в pgAdmin)
      POSTGRES_USER: postgres # имя пользователя (дефолтное для postgres - "postgres")
      POSTGRES_PASSWORD: root # пароль пользователя (дефолтное для postgres - "root")
      POSTGRES_PORT: 5432 # порт POSTGRES-сервера (дефолтное для postgres - "5432")
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d book_store
      interval: 2s
      timeout: 20s
      retries: 10

  db_migrations:
    container_name: migrations
    image: migrate/migrate
    volumes:
      - ./database/migrations:/migrations
    command: -path=/migrations -database postgres://postgres:root@db/book_store?sslmode=disable up
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
